[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install", "npm run build", "npx prisma generate", "npx prisma db push --skip-generate --accept-data-loss"]

[start]
cmd = "node dist/app.js"

