[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev", "npm run build", "npx prisma generate", "npx prisma db push --skip-generate --accept-data-loss"]

[start]
cmd = "node dist/app.js"

